In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,50,(4,6))
arr

array([[ 1, 42, 12, 34, 24, 37],
       [24, 14, 43, 38, 34, 37],
       [47, 36, 36,  6, 13, 10],
       [33, 29,  7, 41,  1, 49]])

In [3]:
print('Mean of the array: ',arr.mean(axis=0))

Mean of the array:  [26.25 30.25 24.5  29.75 18.   33.25]


In [4]:
print('Standard Deviation of the array: ',arr.std(axis=1))

Standard Deviation of the array:  [14.49137675  9.7752522  15.57419518 17.29804099]


In [5]:
print('Variance of the array: ',arr.var(axis=1))

Variance of the array:  [210.          95.55555556 242.55555556 299.22222222]


In [16]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
np.argsort(B)

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5])

In [13]:
f = B.sort()
f

In [22]:
m = int(input("Enter the first value"))
n = int(input("Enter the Second value"))
arr1 = np.random.randint(1,100,(m,n))
print(arr1)
print("Shape ",arr1.shape)
print("dtype ",arr1.dtype)
arr1 = arr1.reshape((n,m))
print(arr1)

Enter the first value3
Enter the Second value4
[[83 26 11 74]
 [67 38 31 32]
 [54 48 96 83]]
Shape  (3, 4)
dtype  int64
[[83 26 11]
 [74 67 38]
 [31 32 54]
 [48 96 83]]


In [ ]:
x = np.array([1, 0, 3, 4])
print("ORIGINAL ARRAY ::--> ",x)
print("\nTest if none of the elements of the said array is zero ::--> ", np.all(x))

res = np.where(x == 0)[0]
print("The index of the  zero elements is :: ",res)


x = np.array([1, 0, 0, 3, 2, 0])
print("\n-------------------------------------------------------")
print("\nORIGINAL ARRAY ::--> ",x)
print("\nTest whether any of the elements of a given array is non-zero ::",np.any(x))
res = np.where(x != 0)[0]
print("The index of the non- zero elements is :: ",res)
x = np.array([0, 0, 0, 0])


a = np.array([1, 0, np.nan, 3, np.nan])
print("\n-------------------------------------------------------")
print("\nORIGINAL ARRAY ::--> ",a)
print("\nTest element-wise for NaN :: ",np.isnan(a))

res = np.where(np.isnan(a) == True)[0]
print("The index of the  zero elements is :: ",res)